server:
  port: 9527

spring:
  application:
    name: springcloud-zuul


# 将路由网关zuul  注册到eureka里面
eureka:
  client:
    service-url:
      # 集群：
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: zuul9527.com
    # 隐藏真实ip
    prefer-ip-address: true


info:
  app.name: ren-springcloud
  company.name: blog.ren.com


# 过滤
zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/**
  ignored-services: springcloud-provider-dept   # 不能再使用这个路径访问了  ,配置"*" 表示隐藏全部的
  prefix: /qianzui    # 设置公共的前缀